name: CD - Dev (build, push, deploy)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-web:
    if: ${{ hashFiles('apps/web/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push web
        uses: docker/build-push-action@v6
        with:
          context: apps/web
          file: apps/web/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/ai-mp-web:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/ai-mp-web:latest

  build-api:
    if: ${{ hashFiles('services/api/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push api
        uses: docker/build-push-action@v6
        with:
          context: services/api
          file: services/api/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/ai-mp-api:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/ai-mp-api:latest

  build-worker:
    if: ${{ hashFiles('services/worker/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push worker
        uses: docker/build-push-action@v6
        with:
          context: services/worker
          file: services/worker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/ai-mp-worker:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/ai-mp-worker:latest

  deploy-web:
    if: ${{ hashFiles('apps/web/**') != '' && hashFiles('helm/web/**') != '' }}
    needs: [build-web]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG_B64}" | base64 -d > ~/.kube/config
        env: { KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }} }
      - name: Ensure namespace + regcred
        run: |
          kubectl create namespace "${K8S_NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n "${K8S_NAMESPACE}" create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username="${REGISTRY_USERNAME}" \
            --docker-password="${REGISTRY_PASSWORD}" \
            --docker-email="devnull@example.com" \
            --dry-run=client -o yaml | kubectl apply -f -
        env:
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Deploy web (Helm)
        run: |
          helm upgrade --install web ./helm/web -n "${K8S_NAMESPACE}" \
            --set image.repository="ghcr.io/${{ github.repository_owner }}/ai-mp-web" \
            --set image.tag="${{ github.sha }}" \
            --set ingress.host="${WEB_HOST}" \
            --set env.NEXT_PUBLIC_API_URL="https://${API_HOST}"
        env:
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          WEB_HOST: ${{ vars.WEB_HOST }}
          API_HOST: ${{ vars.API_HOST }}

  deploy-api:
    if: ${{ hashFiles('services/api/**') != '' && hashFiles('helm/api/**') != '' }}
    needs: [build-api]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG_B64}" | base64 -d > ~/.kube/config
        env: { KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }} }
      - name: Ensure namespace + regcred
        run: |
          kubectl create namespace "${K8S_NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n "${K8S_NAMESPACE}" create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username="${REGISTRY_USERNAME}" \
            --docker-password="${REGISTRY_PASSWORD}" \
            --docker-email="devnull@example.com" \
            --dry-run=client -o yaml | kubectl apply -f -
        env:
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Deploy api (Helm)
        run: |
          helm upgrade --install api ./helm/api -n "${K8S_NAMESPACE}" \
            --set image.repository="ghcr.io/${{ github.repository_owner }}/ai-mp-api" \
            --set image.tag="${{ github.sha }}" \
            --set ingress.host="${API_HOST}"
        env:
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          API_HOST: ${{ vars.API_HOST }}

  deploy-worker:
    if: ${{ hashFiles('services/worker/**') != '' && hashFiles('helm/worker/**') != '' }}
    needs: [build-worker]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG_B64}" | base64 -d > ~/.kube/config
        env: { KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }} }
      - name: Ensure namespace + regcred
        run: |
          kubectl create namespace "${K8S_NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n "${K8S_NAMESPACE}" create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username="${REGISTRY_USERNAME}" \
            --docker-password="${REGISTRY_PASSWORD}" \
            --docker-email="devnull@example.com" \
            --dry-run=client -o yaml | kubectl apply -f -
        env:
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Deploy worker (Helm)
        run: |
          helm upgrade --install worker ./helm/worker -n "${K8S_NAMESPACE}" \
            --set image.repository="ghcr.io/${{ github.repository_owner }}/ai-mp-worker" \
            --set image.tag="${{ github.sha }}"
        env:
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
